{{- if .Values.coreData.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.coreData.configMapName }}
  labels:
    app: {{ .Values.coreData.name }}
data:
  core_data_config.yaml: |
    Service:
      Name: core-data
      Version: "3.1.0"
      Host: "0.0.0.0"
      Port: {{ .Values.coreData.service.port }}
{{- end }}