{{- if .Values.coreData.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.coreData.name }}
  labels:
    app: {{ .Values.coreData.name }}
spec:
  replicas: {{ .Values.coreData.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.coreData.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.coreData.name }}
    spec:
      containers:
        - name: coredata
          image: {{ .Values.coreData.image.repository }}:{{ .Values.coreData.image.tag }}
          imagePullPolicy: {{ .Values.coreData.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.coreData.service.port }}
              name: http
            - containerPort: {{ .Values.coreData.service.adminPort }}
              name: http-admin
          volumeMounts:
            - name: common-config-volume
              mountPath: /etc/edgex/common_config.yaml
              subPath: common_config.yaml
            - name: core-data-config-volume
              mountPath: /res/core_data_config.yaml
              subPath: core_data_config.yaml  # Mount specific file from ConfigMap
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: EDGEX_CONFIG_PROVIDER
              value: "none"
            - name: EDGEX_USE_REGISTRY
              value: "false"
            - name: EDGEX_COMMON_CONFIG
              value: "/etc/edgex/common_config.yaml"
            - name: EDGEX_CONFIG_FILE
              value: "core_data_config.yaml"
          startupProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreData.service.port }}
            failureThreshold: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreData.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreData.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config  # Reference to the common-config ConfigMap
        - name: core-data-config-volume
          configMap:
            name: edgex-core-data-config  # Reference to the core-data-specific ConfigMap            
{{- end }}