{{- if .Values.coreData.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.coreData.name }}
  labels:
    app: {{ .Values.coreData.name }}
spec:
  ports:
    - port: {{ .Values.coreData.service.port }}
      targetPort: {{ .Values.coreData.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.coreData.service.adminPort }}
      targetPort: {{ .Values.coreData.service.adminPort }}
      protocol: TCP
      name: http-admin
  type: {{ .Values.coreData.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.coreData.name }}
{{- end }}