{{- if .Values.coreCommand.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-command-config
data:
  core-command-config.yaml: |
    # Core Command Configuration
    # Define any specific configurations for core-command here.
    # Example configuration:
    Service:
      Name: core-command
      Version: "3.1.0"
    
{{- end }}
