{{- if .Values.coreCommand.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.coreCommand.name | default "core-command" }}
spec:
  replicas: {{ .Values.coreCommand.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.coreCommand.name | default "core-command" }}
  template:
    metadata:
      labels:
        app: {{ .Values.coreCommand.name | default "core-command" }}
    spec:
      serviceAccountName: {{ .Values.coreCommand.name | default "core-command" }}-service-account  # Corrected typo
      containers:
        - name: {{ .Values.coreCommand.name | default "core-command" }}
          image: "{{ .Values.coreCommand.image.repository }}:{{ .Values.coreCommand.image.tag }}"
          resources:
            requests:
              memory: "{{ .Values.coreCommand.resources.requests.memory }}"
              cpu: "{{ .Values.coreCommand.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.coreCommand.resources.limits.memory }}"
              cpu: "{{ .Values.coreCommand.resources.limits.cpu }}"
          startupProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreCommand.service.port }}
            failureThreshold: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreCommand.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreCommand.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: common-config-volume
              mountPath: /etc/edgex/common_config.yaml
              subPath: common_config.yaml
            - name: core-command-config-volume
              mountPath: /res/core_command_config.yaml
              subPath: core_command_config.yaml  # Mount specific file from ConfigMap
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: EDGEX_CONFIG_PROVIDER
              value: "none"
            - name: EDGEX_USE_REGISTRY
              value: "false"
            - name: EDGEX_COMMON_CONFIG
              value: "/etc/edgex/common_config.yaml"
            - name: EDGEX_CONFIG_FILE
              value: "core_command_config.yaml"
          ports:
            - containerPort: 48081
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config  # Reference to the common-config ConfigMap
        - name: core-command-config-volume
          configMap:
            name: core-command-config  # Reference to the core-command-specific ConfigMap
{{- end }}
