{{- if .Values.coreCommand.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: core-command
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-command
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale based on 50% CPU utilization
{{- end }}
