{{- if .Values.coreCommand.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.coreCommand.name | default "core-command" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.coreCommand.name | default "core-command" }}
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.coreCommand.autoscaling.cpuAverageUtilization | default 50 }}  # Scale based on 50% CPU utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.coreCommand.autoscaling.memoryAverageUtilization | default 50 }}  # Scale based on 50% memory utilization
{{- end }}
