{{- if .Values.coreCommand.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.coreCommand.name | default "core-command" }}
spec:
  ports:
    - port: {{ .Values.coreCommand.service.port }}
      targetPort: {{ .Values.coreCommand.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.coreCommand.name | default "core-command" }}
  type: {{ .Values.coreCommand.service.type | default "ClusterIP" }}
{{- end }}
