apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: device-zhonghong
  labels:
    app: {{ .Release.Name }}-device-zhonghong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-zhonghong
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50