{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.redis" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  ports:
    - port: 6379
  selector:
{{ include "chart.labels" . | indent 4 }}
    component: redis
{{- end -}}
