apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: |
    all-services:
      Logging:
        Level: INFO
        EnableFileLogging: true

      Service:
        HealthCheckInterval: "10s"
        Host: "localhost"
        ServerBindAddr: "" # Leave blank so default to Host value unless different value is needed.
        MaxResultCount: 1024
        MaxRequestSize: 0 # Not currently used. Defines the maximum size of http request body in bytes
        RequestTimeout: "5s"
        CORSConfiguration:
          EnableCORS: false
          CORSAllowCredentials: false
          CORSAllowedOrigin: "*" # TBD what's the right config for k8s env?
          CORSAllowedMethods: "GET, POST, PUT, PATCH, DELETE"
          CORSAllowedHeaders: "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
          CORSExposeHeaders: "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
          CORSMaxAge: 3600
      
      Database: 
        Host: "edgex-redis" # TBD sync with redis deployment name
        Port: 6379
        Timeout: "5s"
        Type: "redisdb"
      
      MessageBus:
        Protocol: "tcp"
        Host: "edgex-mqtt" # TBD sync with mqtt deployment name
        Port: 1883
        Type: "mqtt"
        AuthMode: "none"  # required for redis MessageBus (secure or insecure).
        SecretName: ""
        Optional:
          # Default MQTT Specific options that need to be here to enable environment variable overrides of them
          Qos:  "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
          KeepAlive: "10" # Seconds (must be 2 or greater)
          Retained: "false"
          AutoReconnect: "true"
          ConnectTimeout: "5" # Seconds
          SkipCertVerify: "true"
