{{- if .Values.coreMetadata.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-metadata-config
data:
  core_metadata_config.yaml: |
    # Core Metadata Configuration
    # Define any specific configurations for core-metadata here.
    service:
      name: core-metadata
      version: "3.1.0"
      Host: "0.0.0.0"
      Port: {{ .Values.coreMetadata.service.port }}
      AdminPort: {{ .Values.coreMetadata.service.adminPort }}
{{- end }}
