{{- if .Values.coreMetadata.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-metadata-config
data:
  core-metadata-config.yaml: |
    # Core Metadata Configuration
    # Define any specific configurations for core-metadata here.
    service:
      name: core-metadata
      version: "3.0.0"
    database:
      type: redis
      host: redis-service
      port: 6379
    logging:
      level: info
      enableFileLogging: true
{{- end }}
