{{- if .Values.coreMetadata.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-metadata
spec:
  replicas: {{ .Values.coreMetadata.replicas }}
  selector:
    matchLabels:
      app: core-metadata
  template:
    metadata:
      labels:
        app: core-metadata
    spec:
      serviceAccountName: core-metadata-service-account  # Reference the ServiceAccount
      containers:
        - name: core-metadata
          image: "{{ .Values.coreMetadata.image.repository }}:{{ .Values.coreMetadata.image.tag }}"
          resources:
            requests:
              memory: "{{ .Values.coreMetadata.resources.requests.memory }}"
              cpu: "{{ .Values.coreMetadata.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.coreMetadata.resources.limits.memory }}"
              cpu: "{{ .Values.coreMetadata.resources.limits.cpu }}"
          startupProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreMetadata.service.port }}
            failureThreshold: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreMetadata.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/v3/ping
              port: {{ .Values.coreMetadata.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: common-config-volume
              mountPath: /etc/edgex/common_config.yaml
              subPath: common_config.yaml
            - name: core-metadata-config-volume
              mountPath: /res/core_metadata_config.yaml
              subPath: core_metadata_config.yaml  # Mount specific file from ConfigMap
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: EDGEX_CONFIG_PROVIDER
              value: "none"
            - name: EDGEX_USE_REGISTRY  
              value: "false"
            - name: EDGEX_COMMON_CONFIG
              value: "/etc/edgex/common_config.yaml"
            - name: EDGEX_CONFIG_FILE
              value: "core_metadata_config.yaml"
          ports:
            - containerPort: 48081
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config  # Reference to the common-config ConfigMap
        - name: core-metadata-config-volume
          configMap:
            name: core-metadata-config  # Reference to the core-metadata-specific ConfigMap
{{- end }}
