{{- if .Values.coreMetadata.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: core-metadata
spec:
  ports:
    - port: {{ .Values.coreMetadata.service.port }}
      targetPort: {{ .Values.coreMetadata.service.port }}
      protocol: TCP
  selector:
    app: core-metadata
{{- end }}
